// PR-20 scaffold: Next.js App Router root layout. Extend with providers
// (Clerk, TanStack Query client, theme) once real dependencies exist.
import type { Metadata } from "next";
import type { ReactNode } from "react";

export const metadata: Metadata = {
  title: "mawaqit-masjid",
  description: "Generated by Forge — Next.js root layout",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
